class NPITerminals():
    def __init__(self):
        self.terminals = {'D':['the'],
                          'SD': ['the',
                                 'some'],
                          'IC':['that'],
                          'C': ['that'],
                          'MOST':['most',
                                  'many'],
                          'NO':['no',
                                'few'],
                          'MS':['authors',
                                'pilots',
                                'surgeons',
                                'farmers',
                                'managers',
                                'customers',
                                'officers',
                                'teachers',
                                'senators',
                                'consultants'],
                          'ES':['guards',
                                'chefs',
                                'architects',
                                'skaters',
                                'dancers',
                                'ministers',
                                'drivers',
                                'assistants',
                                'executives',
                                'parents'],
                          'IS':['movies',
                                'books',
                                'games',
                                'songs',
                                'pictures',
                                'paintings',
                                'novels',
                                'poems',
                                'shows'],
                          'EV':['like',
                                'admire',
                                'hate',
                                'love'],
                          'PASTAUX':['have'],
                          'FUTAUX':['will'],
                          'NPI':['ever'],
                          'IPMV':['been seen',
                                  'been appreciated'
                                  'been ignored',
                                  'gotten old'],
                          'IFMV':['be seen',
                                  'be appreciated',
                                  'be ignored',
                                  'get old'],
                          'APMV':['been popular',
                                  'been famous',
                                  'had children'],
                          'AFMV':['be popular',
                                  'be famous',
                                  'have children'],
                          'MV':[],
                          'LMV':[]}

class AgreementTerminals():
    def __init__(self):
        self.terminals = {'D':['the'],
                          'IC': ['that'],
                          'C':['that'],
                          'MS':['author',
                                'pilot',
                                'farmer',
                                'painter', 
                                'manager',
                                'customer',
                                'officer',
                                'teacher',
                                'senator',
                                'doctor', 
                                'engineer', 
                                'worker', 
                                'student', 
                                'researcher'
                                ],
                          'ES':['guard',
                                'architect',
                                'dancer',
                                'artist',
                                'minister',
                                'taxi driver',
                                'executive',
                                'parent'],
                          'IS':['movie',
                                'book',
                                'game',
                                'song',
                                'picture',
                                'painting',
                                'novel',
                                'poem',
                                'show'],
                          'MV':['lives',
                                'runs', 
                                'speaks', 
                                'thinks', 
                                'walks', 
                                'is tall',
                                'is old',
                                'is young',
                                'is short', 
                                'is happy', 
                                'is sad', 
                                'is angry'],
                          'EV':['likes',
                                'loves'],
                          'IV':['is good',
                                'is bad',
                                'is new',
                                'is popular',
                                'is unpopular',
                                'brings joy to people',
                                'interests people'],
                          'P':['next to',
                               'behind',
                               'in front of',
                               'near',
                               'to the side of',
                               'across from'],
                          'IP':['from',
                                'by'],
                          'BS':['mechanic',
                                'banker'],
                          'BV':['said',
                                'thought',
                                'knew'],
                          'AND':['and'],
                          'ANPHR': ['himself',
                                    'herself'],
                          'LMV':['knows many different foreign languages',
                                 'likes to watch television shows',
                                 'is twenty three years old',
                                 'enjoys playing tennis with colleagues',
                                 'writes in a journal every day'],
                          'RMV':['hurt',
                                 'injured',
                                 'congratulated',
                                 'embarrassed',
                                 'disguised',
                                 'hated',
                                 'doubted']}
